### ISSUE TITLE
Why delete the Starter Pack Listings?

### ISSUE THREAD

**Issue by sirvon** [prayash/awesome-gatsby#2]
This [listing](https://github.com/prayasht/awesome-gatsby/commit/a52829dacd960b5845743034994998bec0888e74#diff-04c6e90faac2675aa89e2176d2eec7d8L25) of starter packs albeit small, is still like one of the only ones available.

**Comment by prayash** [comment]
@sirvon The official website has updated starter kits, and the old ones were actually from v0. 
Per https://github.com/gatsbyjs/gatsby/issues/1461, I'm going to be moving all this content to the gatsbyjs official GitHub page.

**Comment by sirvon** [comment]
thanks for your response!
